### ISSUE TITLE
Need some simple `autoplot` functionality.

### ISSUE THREAD

**Issue by spsanderson** [spsanderson/RandomWalker#33]
_Example:_
```r
library(RandomWalker)

df <- rw30()
head(df)
atb <- attributes(df)

df |>
  dplyr::group_by(walk_number) |>
  dplyr::mutate(
    distance = sqrt((x - dplyr::lag(x,1))^2 + (y - dplyr::lag(y,1))^2)
  ) |>
  dplyr::mutate(distance = ifelse(is.na(distance), NA_real_, distance)) |>
  dplyr::ungroup() |> 
  tidyr::drop_na() |>
  ggplot2::ggplot(ggplot2::aes(x = x, y = distance, group = walk_number)) +
  ggplot2::geom_line(alpha = .2) +
  ggplot2::theme_minimal() +
  ggplot2::theme(legend.position = "none") +
  ggplot2::labs(
    title = paste0(atb$num_walks, " Random Walks"),
    subtitle = paste0("Distance between steps for each walk ",
                      "calculated as the Euclidean distance between ",
                      "consecutive steps."),
    caption = paste0(atb$dimension, " dimensions, ", atb$num_steps, " steps, ",
                     "mu = ", atb$mu, ", sd = ", atb$sd, "."),
    x = "Step",
    y = "Distance",
    color = "Walk Number"
  )
  
df |>
  dplyr::group_by(walk_number) |>
  dplyr::mutate(
    distance = sqrt((x - dplyr::lag(x,1))^2 + (y - dplyr::lag(y,1))^2)
  ) |>
  dplyr::mutate(distance = ifelse(is.na(distance), NA_real_, distance)) |>
  dplyr::ungroup() |> 
  tidyr::drop_na() |>
  ggplot2::ggplot(ggplot2::aes(x = x, y = distance, group = walk_number,
                               color = as.numeric(walk_number))) +
  ggplot2::geom_line(alpha = .2) +
  ggplot2::theme_minimal() +
  ggplot2::theme(legend.position = "none") +
  ggplot2::labs(
    title = paste0(atb$num_walks, " Random Walks"),
    subtitle = paste0("Distance between steps for each walk ",
                      "calculated as the Euclidean distance between ",
                      "consecutive steps."),
    caption = paste0(atb$dimension, " dimensions, ", atb$num_steps, " steps, ",
                     "mu = ", atb$mu, ", sd = ", atb$sd, "."),
    x = "Step",
    y = "Distance",
    color = "Walk Number"
  )
```

![image](https://github.com/user-attachments/assets/a154b07b-972b-46de-9b5a-54265958cb8d)

![image](https://github.com/user-attachments/assets/740a6e78-718d-496a-93ef-7948d088ccce)

**Comment by spsanderson** [comment]
https://www.cynthiahqy.com/posts/ggplot-helper-design/

https://github.com/EvaMaeRey/ggcalendar/tree/3b0f320de6264b1890b17a4636fe1131194313b1

**Comment by cynthiahqy** [comment]
> I'm looking for a nice way to specify color that could be either inside of the aes() if it is something like walk_number or outside of the aes() if it is something like "grey" but only have a single function argument like .color = NULL

You might consider still using the list format, but moving colour into `geom_line` and exposing it in the `.geom` list argument. You could choose for the default to be either a mapping or direct argument using either:
- `.geom = list(geom_line(mapping = aes(walk_number), alpha = 0.2)` OR
- `.geom = list(geom_line(color = "grey", alpha = 0.2)`
and documenting the other option.

This is clearer than a `.color` option as it places the option in the specific context of `geom_line()`, and won't lead to inconsistent effects on additional geoms. Mappings of the form `ggplot(aes(color = walk_number)) would be passed on by default to something like `+ geom_point()` but direct specification are never passed on -- if both color mapping and direct specification are collapsed into a single argument like `.color` this will be hidden and difficult to debug for users.

**Comment by spsanderson** [comment]
This is a new line of thinking for me. I have an idea of basic plots that could be made for each function, I'll have to sketch out how I see them working to see if it makes sense.

**Comment by AnttiRask** [comment]
@spsanderson, I think the visualize_walks() function is close to what you had in mind, but I do like what @cynthiahqy wrote about the colors and will want to explore that line in the next versions of the function.
