### ISSUE TITLE
Enhance `visualize_walks()`

### ISSUE THREAD

**Issue by spsanderson** [spsanderson/RandomWalker#64]
**Function Enhancement**

We should update the current `visualize_walks()` function with the following parameters:
1. `.interactive`
2. `.pluck`

The `.interactive` parameter should be a boolearn `TRUE / FALSE`. When `TRUE` an interactive `ggiraph` plot should be created as it is compatible with `patchwork`

The `.pluck` parameter should work by capturing the desired plot from the output of `visualize_walks()`, where the following should comeout:
1. `'1'` = `y`
2. `'2'` = `cum_sum`
3. `'3'` = `cum_prod`
4. `'4'` = `cum_min`
5. `'5'` = `cum_max`
6. `'6'` = `cum_mean`

- [x] `.interactive` function and parameter to `visualize_walks`
- [x] `.pluck` parameter to pick which plot someone wants if they only want 1. maybe this can work by if it is valued that only that plot is generated?

**Comment by AnttiRask** [comment]
@spsanderson, found one more bug in the new feature. I'll continue with it tomorrow. I'll let you know when it's ready to check!
