### ISSUE TITLE
Create vignette for the Getting Started with RandomWalker

### ISSUE THREAD

**Issue by spsanderson** [spsanderson/RandomWalker#72]
Hi @AnttiRask we spoke about it but I wanted to turn it into an issue for Documentation. Update the getting started vignette for the package and once done issue a pr, i'll merge and continue the CRAN submission.

Many thanks for your contribution to this project! 

I set a due date, let me know if you will need more time and either go ahead and adjust or just tell me how long to push it out.

**Comment by spsanderson** [comment]
@AnttiRask are you able to change settings on the site, like status?

**Comment by spsanderson** [comment]
Hi @AnttiRask just wanted to see how this is coming along. I would like to submit to CRAN on this Friday August 16, 2024, I have the check list ready to go. Let me know if you need help etc.

**Comment by AnttiRask** [comment]
@spsanderson, I'm sorry about the radio silence! As I mentioned before starting the project, I just started at the new job and it has taken most of my time and energy in the past couple of weeks.

I will try to get everything needed done now, but wanted to make sure if there was anything else besides updating the getting started vignette that needed something from me?

If everything goes according to plan, I should be able to finish the documentation by Sunday August 25th.

**Comment by spsanderson** [comment]
No problem at all i thought you were either busy or on that vacation you had mentioned and as i mentioned i just put a date out there and didn't know if it was a feasible one or not.

Hope the new job is going well!

**Comment by spsanderson** [comment]
That is a good vignette and yes if you can write something similar that would be awesome and then ill add to it my own thoughts 

What do you think?

**Comment by spsanderson** [comment]
hi @AnttiRask I know you have mentioned that your new job is taking quite a bit of energy at the moment, would you like me to complete this task for now?
