### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by jrdnbradford** [spsanderson/RandomWalker#84]
Looks like a copy/paste error in the install instructions. References installing {TidyDensity} from CRAN instead of {RandomWalker}:

![image](https://github.com/user-attachments/assets/6b19e234-f351-4908-9403-29fd9c5e1cfc)

**Comment by spsanderson** [comment]
Actually it's not a typo, it just should not even be there yet. I'm still in the waiting list at CRAN for a human to review my submission. If you want to install while not on cran you can use `pak` or the `devtools` install.

**Comment by spsanderson** [comment]
Closing this issue for now as I do anticipate it's release to CRAN soon and for that reason I'm going to currently leave as is.

**Comment by spsanderson** [comment]
Oh good lord. Let me fix. I don't know how I missed that in your prior message.

**Comment by jrdnbradford** [comment]
😆 no worries. Just wanted to make sure I was clear on this as I thought this might make things more complicated for the CRAN release. Cool package!
